/*  File: nace.h
 *  Author: Fred Wobus (fw@sanger.ac.uk)
 *  Copyright (c) J Thierry-Mieg and R Durbin, 1999
 * -------------------------------------------------------------------
 * Acedb is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 * or see the on-line version at http://www.gnu.org/copyleft/gpl.txt
 * -------------------------------------------------------------------
 * This file is part of the ACEDB genome database package, written by
 * 	Richard Durbin (Sanger Centre, UK) rd@sanger.ac.uk, and
 *	Jean Thierry-Mieg (CRBM du CNRS, France) mieg@kaa.crbm.cnrs-mop.fr
 *
 * Description: Please do not edit this file.
 *		It was generated using rpcgen.
 * Exported functions: See XXXXXXXXXXXXX.h
 * HISTORY:
 * Last edited: Aug 26 17:34 1999 (fw)
 * Created: Thu Aug 26 17:33:58 1999 (fw)
 * CVS info:   $Id: nace.h,v 1.3 1999-09-01 11:14:54 fw Exp $
 *-------------------------------------------------------------------
 */

#include <rpc/types.h>


struct net_data {
	char *cmd;
	struct {
		u_int reply_len;
		char *reply_val;
	} reply;
	int clientId;
};
typedef struct net_data net_data;
bool_t xdr_net_data();

struct ace_server_res {
	int errno;
	union {
		net_data res_data;
	} ace_server_res_u;
};
typedef struct ace_server_res ace_server_res;
bool_t xdr_ace_server_res();

#define NET_ACE ((u_long)0x20000101)
#define NET_ACE_VERS ((u_long)1)
#define ACE_SERVER ((u_long)1)
extern ace_server_res *ace_server_1();
