/*  $Id: nace_clnt.c,v 1.1 1994-08-03 20:02:21 rd Exp $  */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "nace.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

ace_server_res *
ace_server_1(argp, clnt)
	net_data *argp;
	CLIENT *clnt;
{
	static ace_server_res res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, ACE_SERVER, xdr_net_data, argp, xdr_ace_server_res, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}
