/*  $Id: nace_xdr.c,v 1.1 1994-08-03 20:02:29 rd Exp $  */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "nace.h"

bool_t
xdr_net_data(xdrs, objp)
	XDR *xdrs;
	net_data *objp;
{
	if (!xdr_string(xdrs, &objp->cmd, ~0)) {
		return (FALSE);
	}
	if (!xdr_bytes(xdrs, (char **)&objp->reply.reply_val, (u_int *)&objp->reply.reply_len, ~0)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->clientId)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ace_server_res(xdrs, objp)
	XDR *xdrs;
	ace_server_res *objp;
{
	if (!xdr_int(xdrs, &objp->errno)) {
		return (FALSE);
	}
	switch (objp->errno) {
	case 0:
		if (!xdr_net_data(xdrs, &objp->ace_server_res_u.res_data)) {
			return (FALSE);
		}
		break;
	}
	return (TRUE);
}
