/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcace.h"

bool_t
xdr_ace_data(xdrs, objp)
	register XDR *xdrs;
	ace_data *objp;
{

	register long *buf;

	if (!xdr_string(xdrs, &objp->question, ~0))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->reponse.reponse_val, (u_int *) &objp->reponse.reponse_len, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->clientId))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->magic))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ace_reponse(xdrs, objp)
	register XDR *xdrs;
	ace_reponse *objp;
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->errno))
		return (FALSE);
	switch (objp->errno) {
	case 0:
		if (!xdr_ace_data(xdrs, &objp->ace_reponse_u.res_data))
			return (FALSE);
		break;
	}
	return (TRUE);
}
