#!/bin/sh 

# Use system-wide one identified by $1

pkg_config='pkg-config'

if [ "$1" == '-local' ] ; then				    # quotes protect the "-" in -local
  local_path=$2
  shift ; shift
  pkg_config="$local_path/bin/$pkg_config"
  PKG_CONFIG_PATH="$local_path/lib/pkgconfig"
  export PKG_CONFIG_PATH
fi

PKG_CONFIG_PATH="$1/lib/pkgconfig"
export PKG_CONFIG_PATH

$pkg_config --libs $1 $2

exit 0
