#!/usr/local/bin/gawk -f
#
# script to convert ace2 Restriction objects to ace4 Motif
#
# $Id: Restriction2Motif,v 1.1 1995-05-18 23:12:45 esr Exp $


/^Isoschizomers/ { 
  for (i=2; i<=NF; i++) print "Isoschizomer", $i
  next
}

{ 
  gsub ("Restriction", "Motif")
  gsub ("Site", "Match_sequence")
  print 
}
