#!/usr/local/bin/perl -i
#
# removes -O usersession data and big pointless keysets
# particularly good for dumps
#
# $Id: rm-O,v 1.1 1996-10-28 08:44:12 rd Exp $

while (<>) {
    /^ -O / && next ;
    /^-D -O / && next ;
    s/-O \"19.*// ;
    if (/^KeySet : \"new-19/ || /^KeySet : \"touched-19/ || 
	/^KeySet : \"_lexh/ || /^KeySet : \"DoNotDump/) { $reject = 1 ; }
    if (/^\s*$/) { undef $reject ;}
    $reject && next ;
    print ;
}
 
