#!/bin/csh -f

# SCCS: $Id: PfamWWW_script,v 1.1 1996-05-20 19:04:35 esr Exp $

if ("$1" == "") then
  echo Empty URL - aborting
else
  netscape "http://www.sanger.ac.uk/Pfam-bin/family?fam="$1 &
endif
